ocra --no-lzma --no-enc --gem-minimal --no-autoload \
script-sample-tk.rb \
/c/Ruby/lib/tcltk/tcl8.5 \
/c/Ruby/lib/tcltk/tk8.5/button.tcl \
/c/Ruby/lib/tcltk/tk8.5/demos/license.terms \
/c/Ruby/lib/tcltk/tk8.5/entry.tcl \
/c/Ruby/lib/tcltk/tk8.5/listbox.tcl \
/c/Ruby/lib/tcltk/tk8.5/menu.tcl \
/c/Ruby/lib/tcltk/tk8.5/panedwindow.tcl \
/c/Ruby/lib/tcltk/tk8.5/scale.tcl \
/c/Ruby/lib/tcltk/tk8.5/scrlbar.tcl \
/c/Ruby/lib/tcltk/tk8.5/spinbox.tcl \
/c/Ruby/lib/tcltk/tk8.5/text.tcl \
/c/Ruby/lib/tcltk/tk8.5/tk.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/altTheme.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/button.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/clamTheme.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/classicTheme.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/combobox.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/cursors.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/defaults.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/entry.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/fonts.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/menubutton.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/notebook.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/panedwindow.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/progress.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/scale.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/scrollbar.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/sizegrip.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/spinbox.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/treeview.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/ttk.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/utils.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/vistaTheme.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/winTheme.tcl \
/c/Ruby/lib/tcltk/tk8.5/ttk/xpTheme.tcl \
